# Sample workflow for building and deploying a Next.js site to GitHub Pages

name: Deploy Next.js site to Pages

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure Node.js version matches your project requirements

      - name: Install dependencies
        run: npm install  # Adjust if you use Yarn: yarn install

      - name: Build the project
        run: npm run build  # Adjust if you use Yarn: yarn build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-next-app
          path: .next  # Ensure this path matches your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-next-app
          path: .next  # Ensure this path matches the artifact name and location

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next  # Ensure this path matches your build output directory
          enable_jekyll: false  # Disable Jekyll if not needed

